import bindings from 'bindings';
const addon = bindings("addon.node");

// fcntl doesn't exist on Windows, so I have to go around
export const getFdAccessMask = addon.getFdAccessMask as (fd: number) => AccessMask;

export enum AccessMask {
  DELETE = 0x00010000,
  READ_CONTROL = 0x00020000,
  WRITE_DAC = 0x00040000,
  WRITE_OWNER = 0x00080000,
  SYNCHRONIZE = 0x00100000,
  STANDARD_RIGHTS_REQUIRED = 0x000F0000,
  FILE_ADD_FILE = 2,
  FILE_ADD_SUBDIRECTORY = 4,
  FILE_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF),
  FILE_APPEND_DATA = 4,
  FILE_CREATE_PIPE_INSTANCE = 4,
  FILE_DELETE_CHILD = 64,
  FILE_EXECUTE = 32,
  FILE_LIST_DIRECTORY = 1,
  FILE_READ_ATTRIBUTES = 128,
  FILE_READ_DATA = 1,
  FILE_READ_EA = 8,
  FILE_TRAVERSE = 32,
  FILE_WRITE_ATTRIBUTES = 256,
  FILE_WRITE_DATA = 2,
  FILE_WRITE_EA = 16,
  STANDARD_RIGHTS_READ = (READ_CONTROL),
  STANDARD_RIGHTS_WRITE = (READ_CONTROL),
  STANDARD_RIGHTS_EXECUTE = (READ_CONTROL),
  STANDARD_RIGHTS_ALL = 0x001F0000,
  SPECIFIC_RIGHTS_ALL = 0x0000FFFF,
}